/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.findcollege.gui;

import com.findcollege.data.College;
import com.findcollege.data.CollegeData;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ritika
 */
public class FirstPanel extends javax.swing.JFrame {  
    /**
     * Creates new form FirstPanel
     */
    public FirstPanel() {
        searchComboBox = new DefaultComboBoxModel(CollegeData.NAMES.toArray());
        compareComboBox = new DefaultComboBoxModel(CollegeData.chooseData.toArray());
        initComponents();
        TableModel table = getTableModel(CollegeData.Data);
        compareTable.setModel(table);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        textboxScroll = new javax.swing.JScrollPane();
        collegeOutput = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        iconContainer = new javax.swing.JPanel();
        collegeIcon = new javax.swing.JLabel();
        hyperlink = new javax.swing.JLabel();
        collegesList = new javax.swing.JComboBox<>();
        yourTitle = new javax.swing.JLabel();
        collegeTitle = new javax.swing.JLabel();
        searchTitle = new javax.swing.JLabel();
        forTitle = new javax.swing.JLabel();
        comparePanel = new javax.swing.JPanel();
        compareTableScroll = new javax.swing.JScrollPane();
        compareTable = new javax.swing.JTable();
        chooseData = new javax.swing.JComboBox<>();
        sortButton = new javax.swing.JToggleButton();
        compareTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find Your College");
        setBounds(new java.awt.Rectangle(0, 0, 300, 300));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setName("GUI"); // NOI18N

        collegeOutput.setBackground(new java.awt.Color(255, 244, 250));
        collegeOutput.setColumns(20);
        collegeOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        collegeOutput.setForeground(new java.awt.Color(105, 87, 59));
        collegeOutput.setRows(5);
        collegeOutput.setTabSize(9);
        collegeOutput.setToolTipText("Information Displayed");
        collegeOutput.setAlignmentX(2.0F);
        collegeOutput.setAlignmentY(2.0F);
        collegeOutput.setAutoscrolls(false);
        collegeOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 175, 164)));
        collegeOutput.setDragEnabled(true);
        collegeOutput.setName(""); // NOI18N
        collegeOutput.setPreferredSize(new java.awt.Dimension(0, 300));
        collegeOutput.setRequestFocusEnabled(false);
        textboxScroll.setViewportView(collegeOutput);

        searchButton.setForeground(new java.awt.Color(107, 96, 73));
        searchButton.setText("Search");
        searchButton.setToolTipText("click"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        clearButton.setForeground(new java.awt.Color(107, 96, 73));
        clearButton.setText("Clear");
        clearButton.setToolTipText("click");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iconContainerLayout = new javax.swing.GroupLayout(iconContainer);
        iconContainer.setLayout(iconContainerLayout);
        iconContainerLayout.setHorizontalGroup(
            iconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(collegeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        iconContainerLayout.setVerticalGroup(
            iconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconContainerLayout.createSequentialGroup()
                .addComponent(collegeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        hyperlink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        collegesList.setEditable(true);
        collegesList.setForeground(new java.awt.Color(104, 86, 59));
        collegesList.setModel(searchComboBox);
        collegesList.setToolTipText("Enter name or city of school");
        collegesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegesListActionPerformed(evt);
            }
        });

        yourTitle.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        yourTitle.setForeground(new java.awt.Color(104, 86, 59));
        yourTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourTitle.setText("For");

        collegeTitle.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        collegeTitle.setForeground(new java.awt.Color(104, 86, 59));
        collegeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        collegeTitle.setText("College");

        searchTitle.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        searchTitle.setForeground(new java.awt.Color(104, 86, 59));
        searchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchTitle.setText("Search");

        forTitle.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        forTitle.setForeground(new java.awt.Color(104, 86, 59));
        forTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forTitle.setText("Your");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yourTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(forTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(collegeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(collegesList, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(hyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(textboxScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(iconContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(collegesList, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textboxScroll)
                            .addComponent(iconContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(hyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yourTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(collegeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addContainerGap())
        );

        tabContainer.addTab("Search", searchPanel);

        compareTableScroll.setViewportView(compareTable);

        chooseData.setModel(compareComboBox);
        chooseData.setSelectedItem(compareComboBox);
        chooseData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDataActionPerformed(evt);
            }
        });

        sortButton.setText("Change to Descending");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        compareTitle.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        compareTitle.setForeground(new java.awt.Color(104, 86, 59));
        compareTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compareTitle.setText("Compare Your Colleges");

        javax.swing.GroupLayout comparePanelLayout = new javax.swing.GroupLayout(comparePanel);
        comparePanel.setLayout(comparePanelLayout);
        comparePanelLayout.setHorizontalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparePanelLayout.createSequentialGroup()
                .addGroup(comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comparePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(compareTableScroll))
                    .addGroup(comparePanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(chooseData, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(sortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(comparePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(compareTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        comparePanelLayout.setVerticalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compareTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(compareTitle)
                .addGap(31, 31, 31))
        );

        tabContainer.addTab("Compare", comparePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContainer, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void collegesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegesListActionPerformed

    }//GEN-LAST:event_collegesListActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        System.out.println("Cancel Button Clicked");
        collegeOutput.setText(null);
        collegeOutput.setText(null);
        updateCollegeIcon("./pics/entercollegeLogo.png");
        setURL(" ");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        System.out.println("Search Button Clicked");
        List<College> collegeData = findCollege((String)collegesList.getSelectedItem());
        collegeOutput.setText(null);
        if(collegeData.isEmpty()){
            collegeOutput.append(" Please enter a valid College");
            updateCollegeIcon("./pics/notfoundLogo.png");
        }
        else{
            for(College c : collegeData){
                updateCollegeIcon(c.getLogoURL());
                setURL(c.getLink());
                collegeOutput.append( " College Name: \n" + " " + c.getName()
                    + "\n Address: " +  c.getCity()
                    + ", "
                    + c.getState()
                    + " " +c.getZipcode()
                    +"\n Tuition: $" + c.getTuition()
                    + "\n College Size: " + c.getSize() + " people"
                    + "\n Has Bachelors Program? "
                    + c.getHasBachelors()
                    + "\n Has Masters Program? "
                    + c.getHasMasters()
                    + "\n Acceptance Rate: "
                    + c.getAcceptanceRate() + "%"
                    + "\n Graduation Rate: "
                    + c.getGradRate() + "%"
                    + "\n\n");
            }
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void chooseDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDataActionPerformed
        
    }//GEN-LAST:event_chooseDataActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        String fieldSelected = (String)chooseData.getSelectedItem();
        boolean ascending = true;
        if(evt.getActionCommand().equals("Change to Descending")){
            sortButton.setText("Change to Ascending");
            ascending = false;
        }
        else{
            sortButton.setText("Change to Descending");
            ascending = true;
        }
        TableModel sortedTableModel = getSortedTableModel(fieldSelected, ascending);
        compareTable.setModel(sortedTableModel);
    }//GEN-LAST:event_sortButtonActionPerformed

    private TableModel getSortedTableModel(String fieldSelected, boolean ascending){
        List<College> colleges = CollegeData.Data;
        Collections.sort(colleges, new Comparator<College>() {
            @Override
            public int compare(College first, College second) {
                if(fieldSelected.equals("Choose Data")){
                    return 0;
                }
                else if (fieldSelected.equals("School Size") && ascending == false){
                return Integer.compare(first.getSize(), second.getSize())*-1;
                }
                else if(fieldSelected.equals("School Size") && ascending == true){
                return Integer.compare(first.getSize(), second.getSize());
                }
                else if(fieldSelected.equals("Graduation Rate") && ascending == false){
                    return Integer.compare(first.getGradRate(), second.getGradRate())*-1;
                }
                else if(fieldSelected.equals("Graduation Rate") && ascending == true){
                    return Integer.compare(first.getGradRate(), second.getGradRate());
                }
                else if(fieldSelected.equals("Acceptance Rate") && ascending == false){
                    return Integer.compare(first.getAcceptanceRate(), second.getAcceptanceRate())*-1;
                }
                else if(fieldSelected.equals("Acceptance Rate") && ascending == true){
                    return Integer.compare(first.getAcceptanceRate(), second.getAcceptanceRate());
                }
                else if(fieldSelected.equals("Tuition") && ascending == false){
                    return Double.compare(first.getTuition(), second.getTuition())*-1;
                }
                else if(fieldSelected.equals("Tuition") && ascending == true){
                    Double.compare(first.getTuition(), second.getTuition());
                }
                return  Double.compare(first.getTuition(), second.getTuition());
            }
        });
        return getTableModel(colleges);
    }
    
    private void setURL(String link) {
        hyperlink.setForeground(Color.BLUE.darker());
        hyperlink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        hyperlink.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    // the user clicks on the label
                    Desktop.getDesktop().browse(new URI(link));
                } catch (URISyntaxException ex) {
                    Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                // the mouse has entered the label
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                // the mouse has exited the label
            }
        });
        hyperlink.setText(link);
    }
        

    
    private TableModel  getTableModel(List<College> colleges){
        
        int col = 6;
        int row = colleges.size();
        String[][] collArray = new String[row][col];
        for(int i=0;i<row;i++){
            College college = colleges.get(i);
            collArray[i] = new String[]{college.getName(), college.getCity(),
                    ""+ college.getSize(), ""+college.getTuition(), ""+ 
                    college.getAcceptanceRate() , "" + 
                    college.getGradRate() };
        }     
         String[] columns = {"College Name", "City", "School Size (number of students)",
             "Tuition ($)", "Acceptance Rate (%)", "Graduation Rate (%)"};
        
        TableModel tm = new DefaultTableModel(collArray, columns);
        return tm;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPanel().setVisible(true);
            }
        });
    }
    
    public static List<College> findCollege(String textboxValue){
        List<College> colleges = new ArrayList<>();
        for(College college : CollegeData.Data){ //enhanced for loop
            String matchName = college.getName().toLowerCase();
            String matchCity = college.getCity().toLowerCase();
            if(matchName.contains(textboxValue.toLowerCase()) 
                || matchCity.contains(textboxValue.toLowerCase())){
                 colleges.add(college);
            }
        } 
        return colleges;   
    }
    
    private void updateCollegeIcon(String iconURL){
            try {
                URL url = this.getClass().getResource(iconURL);
                ImageIcon x = new ImageIcon(url);
                collegeIcon.setIcon(x);
                collegeIcon.setText(iconURL);
                iconContainer.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    private ComboBoxModel searchComboBox;
    private ComboBoxModel compareComboBox;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseData;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel collegeIcon;
    private javax.swing.JTextArea collegeOutput;
    private javax.swing.JLabel collegeTitle;
    private javax.swing.JComboBox<String> collegesList;
    private javax.swing.JPanel comparePanel;
    private javax.swing.JTable compareTable;
    private javax.swing.JScrollPane compareTableScroll;
    private javax.swing.JLabel compareTitle;
    private javax.swing.JLabel forTitle;
    private javax.swing.JLabel hyperlink;
    private javax.swing.JPanel iconContainer;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel searchTitle;
    private javax.swing.JToggleButton sortButton;
    private javax.swing.JTabbedPane tabContainer;
    private javax.swing.JScrollPane textboxScroll;
    private javax.swing.JLabel yourTitle;
    // End of variables declaration//GEN-END:variables
}
