/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ritikabanepali.gui;

import com.ritikabanepali.data.College;
import com.ritikabanepali.data.CollegeData;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ritik
 */
public class FirstPanel extends javax.swing.JFrame {

    /**
     * Creates new form FirstPanel
     */
    public FirstPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollBar1 = new javax.swing.JScrollBar();
        jMenu4 = new javax.swing.JMenu();
        tabContainer = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        collegeOutput = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        iconContainer = new javax.swing.JPanel();
        collegeIcon = new javax.swing.JLabel();
        hyperlink = new javax.swing.JLabel();
        collegesList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        compareTable = new javax.swing.JTable();
        chooseData = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find Your College");
        setBounds(new java.awt.Rectangle(0, 0, 300, 300));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setName("GUI"); // NOI18N
        setResizable(false);

        collegeOutput.setBackground(new java.awt.Color(255, 244, 250));
        collegeOutput.setColumns(20);
        collegeOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        collegeOutput.setForeground(new java.awt.Color(105, 87, 59));
        collegeOutput.setRows(5);
        collegeOutput.setTabSize(9);
        collegeOutput.setToolTipText("Information Displayed");
        collegeOutput.setAlignmentX(2.0F);
        collegeOutput.setAlignmentY(2.0F);
        collegeOutput.setAutoscrolls(false);
        collegeOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 175, 164)));
        collegeOutput.setDragEnabled(true);
        collegeOutput.setName(""); // NOI18N
        collegeOutput.setPreferredSize(new java.awt.Dimension(0, 300));
        collegeOutput.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(collegeOutput);

        searchButton.setForeground(new java.awt.Color(107, 96, 73));
        searchButton.setText("Search");
        searchButton.setToolTipText("click"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        clearButton.setForeground(new java.awt.Color(107, 96, 73));
        clearButton.setText("Clear");
        clearButton.setToolTipText("click");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iconContainerLayout = new javax.swing.GroupLayout(iconContainer);
        iconContainer.setLayout(iconContainerLayout);
        iconContainerLayout.setHorizontalGroup(
            iconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(collegeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        iconContainerLayout.setVerticalGroup(
            iconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconContainerLayout.createSequentialGroup()
                .addComponent(collegeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        hyperlink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        collegesList.setEditable(true);
        collegesList.setForeground(new java.awt.Color(104, 86, 59));
        collegesList.setModel(model);
        collegesList.setToolTipText("Enter name, state, or city of school");
        collegesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegesListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 86, 59));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your");

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 86, 59));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("College");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(104, 86, 59));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search");

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(104, 86, 59));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("For");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(collegesList, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(hyperlink, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(iconContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(collegesList, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(iconContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(hyperlink, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addContainerGap())
        );

        tabContainer.addTab("Search", jPanel1);

        jScrollPane2.setViewportView(compareTable);

        chooseData.setModel(model2);
        chooseData.setSelectedItem(model2);
        chooseData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDataActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Change to Descending");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(104, 86, 59));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("College");

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(104, 86, 59));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Compare");

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 86, 59));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Your");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(chooseData, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(chooseData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabContainer.addTab("Compare", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContainer, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void collegesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegesListActionPerformed

    }//GEN-LAST:event_collegesListActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        System.out.println("Cancel Button Clicked");
        collegeOutput.setText(null);
        collegeOutput.setText(null);
        updateCollegeIcon("./pics/entercollegeLogo.png");
        setURL(" ");
        TableModel table = getTableModel();
        compareTable.setModel(table);
        // TODO: get rid of scroll bar when less than one college
        // TODO: buttons on compare page
        // TODO: see full size of school in table
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        System.out.println("Search Button Clicked");
        List<College> collegeData = findCollege((String)collegesList.getSelectedItem());
        collegeOutput.setText(null);
        if(collegeData.isEmpty()){
            collegeOutput.append(" Please enter a valid College");
            updateCollegeIcon("./pics/notfoundLogo.png");
        }
        else{
            for(College c : collegeData){
                updateCollegeIcon(c.getLogoURL());
                setURL(c.getLink());
                collegeOutput.append( " College Name: \n" + " " + c.getName()
                    + "\n Address: " +  c.getCity()
                    + ", "
                    + c.getState()
                    + " " +c.getZipcode()
                    +"\n Tuition: $" + c.getTuition()
                    + "\n College Size: " + c.getSize() + "people"
                    + "\n Has Bachelors Program? "
                    + c.getHasBachelors()
                    + "\n Has Masters Program? "
                    + c.getHasMasters()
                    + "\n Acceptance Rate: "
                    + c.getAcceptanceRate() + "%"
                    + "\n Graduation Rate: "
                    + c.getGradRate() + "%"
                    + "\n\n");
            }
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void chooseDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDataActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void setURL(String link) {
        hyperlink.setForeground(Color.BLUE.darker());
        hyperlink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        hyperlink.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    // the user clicks on the label
                    Desktop.getDesktop().browse(new URI(link));
                } catch (URISyntaxException ex) {
                    Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                // the mouse has entered the label
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                // the mouse has exited the label
            }
        });
        hyperlink.setText(link);
    }
        
    ComboBoxModel model = new DefaultComboBoxModel(CollegeData.NAMES.toArray());
    ComboBoxModel model2 = new DefaultComboBoxModel(CollegeData.chooseData.toArray());
    
    private TableModel  getTableModel(){
        
    
        Vector<Vector<String>> data = new Vector<Vector<String>>();
       
           
           
        
        
        //each college
//        Vector<String> firstRow = new Vector<>();
//        firstRow.add("University of Texas at Austin");
//        firstRow.add("2345");
//        firstRow.add("2000.0");
//        firstRow.add("2000.0");
//        firstRow.add("2000.0");
//        data.add(firstRow);
//        Vector<String> second = new Vector<>();
//        second.add("University of Texas at Austin");
//        second.add("2345");
//        second.add("2000.0");
//        second.add("2000.0");
//        second.add("2000.0");
//        data.add(second);
        
          
    
//        String[][] data = {
//            {"University of Texas at Austin", "2345", "20000.0"}, 
//            {"University of Texas at Arlington", "789", "2000.0"}    
//        };
                   
    
        Vector<String> columns = new Vector<String>();
        columns.add("College Name");
        columns.add("City");
        columns.add("School Size");
        columns.add("Acceptance Rate");
        columns.add("Graduation Rate");
        //String[] columns = {"College Name", "Size", "Tuition"};
        
        TableModel tm = new DefaultTableModel(data, columns);
        return tm;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPanel().setVisible(true);
            }
        });
    }
    
    public static List<College> findCollege(String textboxValue){
        List<College> colleges = new ArrayList<>();
        for(College college : CollegeData.Data){ //enhanced for loop
            String matchName = college.getName().toLowerCase();
            String matchCity = college.getCity().toLowerCase();
            String matchState = college.getState().toLowerCase();
            if(matchName.contains(textboxValue.toLowerCase()) 
                || matchCity.contains(textboxValue.toLowerCase())
                || matchState.contains(textboxValue.toLowerCase())){
                 colleges.add(college);
            }
        } 
        return colleges;   
    }
    
    private void updateCollegeIcon(String iconURL){
            try {
                URL url = this.getClass().getResource(iconURL);
                ImageIcon x = new ImageIcon(url);
                collegeIcon.setIcon(x);
                collegeIcon.setText(iconURL);
                iconContainer.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FirstPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseData;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel collegeIcon;
    private javax.swing.JTextArea collegeOutput;
    private javax.swing.JComboBox<String> collegesList;
    private javax.swing.JTable compareTable;
    private javax.swing.JLabel hyperlink;
    private javax.swing.JPanel iconContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTabbedPane tabContainer;
    // End of variables declaration//GEN-END:variables
}
